[project]
authors = ["Dave I."]
channels = ["conda-forge"]
description = "Add a short description here"
name = "py-voyages"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python-dotenv = ">=1.0.1,<2"
flask = ">=3.1.0,<4"
psycopg2 = ">=2.9.9,<3"
fastapi = ">=0.115.11,<0.116"
